### ISSUE TITLE
ImportError: no module named 'sim800.utils'

### ISSUE THREAD

**Issue by jouellnyc** [basanovase/sim800#3]
Howdy. Initial import yields the following. But seems like utils is not to be found in the repo.

```
from sim800 import SIM800
sim800 = SIM800(uart_pin=1, baud=115200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sim800/__init__.py", line 5, in <module>
ImportError: no module named 'sim800.utils'
```

**Comment by ilkerx** [comment]
Ahahaha the guy forgot to push file .utils 👯‍♀️

**Comment by basanovase** [comment]
squashed
